fix(github-actions): `commitlint` checking is not working in the `node` workflow
Error:
- Run npx commitlint --from 1910557fd5aeed0679c1a6b454c14dfc3f1ba5dd --to 8c5c2f34ae0f0f68ec75d6a3af241aba9a89e987 --verbose
/home/runner/work/vue-gh-pages/vue-gh-pages/node_modules/@commitlint/cli/lib/cli.js:123
        throw err;
        ^
Error: fatal: Invalid revision range 1910557fd5aeed0679c1a6b454c14dfc3f1ba5dd..8c5c2f34ae0f0f68ec75d6a3af241aba9a89e987

Reason:
- It appears that the `commits` range being reviewed is incorrect.
The `commitlint` check failed when receiving an invalid revision range on `push` and `pull request` events. It was assumed that there was always a range of `commits` available for checking, which is not the case for `push` or `PR` with a single `commit`.

Solution:
- Include a `commitlint` check that runs on both `pull request` and `push` events.
For `PR`, all `commits` between the base and the head of the PR will be validated to ensure they follow our `commit` message conventions.
For `push`, only the last `commit` will be validated, since locally each `commit` is pre-reviewed.