BUGFIX. The github action to build and test Node.js version 10 does not work.
Error:
- Gets an error when checking the packages with node 10 version.
The error appears to come from stylelint v.14
stylelint@14.0.0: TypeError: [files].flat is not a function
https://github.com/beatrizsmerino/vue-gh-pages/actions/runs/1692012719

Solution:
- Update github workflow for check node on 12, 14 and 16 versions
That's not supported in 10.x. Stylelint requires Node.js 12.20.0+ since v14, so please consider updating your Node.js version.
Therefore I will no longer check the old version 10, and have added the new version 16 instead. So the check will be on versions 12, 14 and 16.
https://github.com/digitalbazaar/vc-js/issues/57
https://node.green/#ES2019-features-Array-prototype--flat--flatMap-
https://issueexplorer.com/issue/stylelint/stylelint/5646