fix(github-actions): `commitlint` continues without working
Error:
- Run if [ "push" = "pull_request" ]; then
/home/runner/work/vue-gh-pages/vue-gh-pages/node_modules/@commitlint/cli/lib/cli.js:123
        throw err;
        ^
Error: fatal: ambiguous argument 'HEAD~1..HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

Solution:
- It has been decided to remove the `commitlint` validation step from our GitHub Actions workflow due to persistent issues with the interpretation of the `commits` range on `push` and `pull request` events. Since we already have `husky` configured to run `commitlint` locally on every `commit`, validation in the workflow has become redundant. This will simplify our continuous integration process and eliminate unnecessary bottlenecks caused by checking ambiguous `commit` ranges on the CI server.